### ISSUE TITLE
Succesfully Build 'mapthepaths-android'

### ISSUE THREAD

**Issue by chrisdebian** [chrisdebian/MOROW#1]
NickW has done good work and created an app that could be a great starting point for MOROW's objectives. 

https://gitlab.com/nickw1/mapthepaths-android

I understand that the code has been unmaintained for 4 years, and as such, has been withdrawn from Google Play. The app is written in Kotlin and is GPLv3. Kotlin can be used for cross-platform apps, and in a quick feature comparison, would be a good foundation for MOROW to build on.

I can't code, but have imported the existing code into Android Studio, and intelliJ IDEA. I updated out of date bits, based purely on IDE suggestions. Unfortunately I still got a Gradle error, so couldn't complete a build. So that we can understand whether we can re-use Nick's code, an essential first step for MOROW, is to prove that the code can be built. If this can't be achieved, it'll be starting from scratch, without any code. If this has to happen, we'll ideally need to use a language that is 'cross-platform', which in the real world, for mobile devices, probably means the target devices will be Android and IOS.

Can anyone try to build Nick's app?

Thanks,

Chris.

**Comment by nickw1** [comment]
Hi @chrisdebian let me try and build it. Will report back.

**Comment by chrisdebian** [comment]
Thanks, @nickw1 , that would be great. I guess that as you are/ we're familiar with the code, you've got a better chance of getting it to build.

Cheers,

Chris

**Comment by nickw1** [comment]
@chrisdebian OK I have now got it to build and run on a recent Android Studio (Jellyfish: last but one version). I performed these steps:

- Updated Gradle and Gradle Wrapper and Android Gradle Plugin to recent versions;
- Incorporated the Ordnance Survey OpenSpace Android SDK dependency directly within the package.

Let me know if it builds for you.

I quickly tested on the emulator. Some functionality works (connecting to and rendering the data from my own MapThePaths server) but logging into and downloading data from the OSM server does not. As I thought, the app needs to be upgraded to OAuth2 though this is likely the place for another issue.

Also it's best I think to replace the OS OpenSpace library with another as it hasn't been updated for a seriously long time. The reason why I used OS OpenData tiles as the base layer was that I didn't have the server resources to setup a UK tileserver. Again the details of this are best placed in another issue

**Comment by nickw1** [comment]
... sorry, you need to use the `morow-investigation` branch in the repo.

**Comment by chrisdebian** [comment]
Thank you so much @nickw1. You've made some reel progress. As you say, not perfect, but those things can be added to the backlog. I'll create some new Issues, hopefully today, then close this one. 

Thanks for working on this,

Chris

**Comment by chrisdebian** [comment]
Brilliant [work](https://gitlab.com/nickw1/mapthepaths-android/-/commits/morow-investigation) by Nick. I'll close this issue and open some new ones to begin to address Nick's findings. 

Thanks, Nick.

Chris.
